services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: liveview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d liveview"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 5433:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

networks:
  postgres-network:
    driver: bridge

volumes:
  pgdata:
